lib: Add CRUD support for HelmRelease,GitRepository
kinvolk/flux-libs pull request #1
Opened 2021-08-20 14:49 UTC by surajssd

2021-09-23 10:15 UTC, surajssd commented
@knrt10 @iaguis can we merge this one so as to close https://github.com/kinvolk/lokomotive/issues/1550 ?

2021-09-23 10:36 UTC, iaguis commented
Let me do a quick review.

2021-09-23 12:53 UTC, iaguis requested changes

2021-09-23 12:53 UTC, iaguis commented on lib/source-controller/lib.go
> +type gitRespoConfigOpt func(*GitRepoConfig)
```suggestion
type gitRepoConfigOpt func(*GitRepoConfig)
```

2021-09-23 12:53 UTC, iaguis commented on lib/client.go
> +package lib
Can we add a license header?

2021-09-23 12:53 UTC, iaguis commented on lib/client.go
> +			return nil, fmt.Errorf("neither kubeconfig not provided nor in-cluster config available: %w", err)
```suggestion
			return nil, fmt.Errorf("kubeconfig not provided and in-cluster config not available: %w", err)
```

2021-09-23 12:53 UTC, iaguis commented on lib/client.go
> +		return nil, fmt.Errorf("creating client config failed: %w", err)
```suggestion
		return nil, fmt.Errorf("creating client config: %w", err)
```

2021-09-23 12:53 UTC, iaguis commented on lib/client.go
> +		return nil, fmt.Errorf("converting client config to rest client config failed: %w", err)
```suggestion
		return nil, fmt.Errorf("converting client config to rest client config: %w", err)
```

2021-09-23 12:53 UTC, iaguis commented on lib/client.go
> +		return nil, fmt.Errorf("creating a REST client: %w", err)
```suggestion
		return nil, fmt.Errorf("creating REST client: %w", err)
```

2021-09-23 12:53 UTC, iaguis commented on lib/doc.go
> +package lib
Ditto about license header

2021-09-23 12:53 UTC, iaguis commented on lib/helm-release/doc.go
> +package helmrelease
Ditto about license header

2021-09-23 12:53 UTC, iaguis commented on lib/helm-release/lib.go
> +package helmrelease
Ditto about license header

2021-09-23 12:53 UTC, iaguis commented on lib/source-controller/doc.go
> +package sourcecontroller
Ditto about license header

2021-09-23 12:53 UTC, iaguis commented on lib/source-controller/lib.go
> +package sourcecontroller
Ditto about... well, I think you get the idea 😂

2021-09-23 12:53 UTC, iaguis commented on lib/helm-release/lib.go
> +	_ = api.AddToScheme(scheme)
Do we need an init() function? I heard they're evil in libraries

2021-10-07 10:54 UTC, surajssd commented on lib/helm-release/lib.go
> +	_ = api.AddToScheme(scheme)
We need this to register those APIs, so as to talk to k8s api-server.

2021-10-07 11:33 UTC, iaguis approved these changes
lgtm

2021-10-07 11:34 UTC, merged